bin.name = "complex"
args = ["whoami", "--verbose"]
status.code = 0
stdout = """
>> Hello world! CommonOpts { debug: 0 }, color: None, database: Database { _data: \"Loads of data\" }, verbosity: Warn
I'm groot!
"""
stderr = ""

