bin.name = "complex"
args = ["calculator", "subtract", "10", "2"]
status.code = 1
stdout = """
>> Hello world! CommonArgs { debug: 0 }, color: None, verbosity: Error
Database is currently Database { _data: \"Loads of data\" } but we will override that!
>> Calculator: Calculator { color: false, operation: Subtract(SubtractArgs { num1: 10, num2: 2 }) }
"""
stderr = """
[[..] TRACE cling] Skipping `CliArgs.use_me` because `bool` doesn't implement `Collect`
[[..] DEBUG cling] Collecting type `clap_verbosity_flag :: Verbosity` from `CliArgs.verbosity` because it's marked with `#[cling(collect)]`. This can be extracted with cling::prelude::Collected<T> at runtime.
[[..] DEBUG cling] Collecting type `Option < Vec < Colors > >` from `CliArgs.colors` because it derives `Collect`
[[..] DEBUG cling] Collecting type `CommonArgs` from `CliArgs.common` because it derives `Collect`
[[..] DEBUG cling] Running handler `init` of type `CliArgs`
[[..] TRACE cling] Skipping `Calculator.color` because `bool` doesn't implement `Collect`
[[..] DEBUG cling] Running handler `run_calc` of type `Calculator`
[[..] TRACE cling] Skipping `SubtractArgs.num1` because `u64` doesn't implement `Collect`
[[..] TRACE cling] Skipping `SubtractArgs.num2` because `u64` doesn't implement `Collect`
[[..] DEBUG cling] Running handler `run_subtract` of type `SubtractArgs`


** Cling Handler Design Error **

In `complex::run_subtract`: Type `&complex::AddArgs` was not collected from input arguments. Possible reasons:
   - The type doesn't implement `Collect` (add #[derive(Collect)])
   - The struct field wasn't marked with `#[cling(collect)]`
   - The type is not present in any fields, enums, or structs leading to this command in the command hierarchy.
   - The type is defined with Option<T> or Vec<T> and you used T, or vice versa

   Those are the types that have been collected: [
    \"cling::extractors::Collected<clap_verbosity_flag::Verbosity>\",
    \"cling::extractors::State<complex::Database>\",
    \"complex::Calculator\",
    \"complex::CliArgs\",
    \"complex::CommonArgs\",
    \"complex::SubtractArgs\",
    \"core::option::Option<alloc::vec::Vec<complex::Colors>>\",
]
   
"""

[env.add]
TERM = "dumb"
RUST_LOG = "trace"
