bin.name = "simple-multi-command"
args = []
status.code = 2
stdout = ""
stderr = """
A simple multi-command example using cling

Usage: simple-multi-command[EXE] [OPTIONS] <COMMAND>

Commands:
  honk  Honk the horn!
  beep  Beep beep!
  help  Print this message or the help of the given subcommand(s)

Options:
  -v, --verbose...  Turn debugging information on
  -h, --help        Print help
  -V, --version     Print version
"""
