bin.name = "simple-multi-command"
args = ["honk"]
status.code = 2
stdout = ""
stderr = """
error: the following required arguments were not provided:
  <TIMES>

Usage: simple-multi-command[EXE] honk <TIMES>

For more information, try '--help'.
"""
