match_arm_leading_pipes = "Always"

group_imports = "StdExternalCrate"
reorder_imports = true
imports_layout = "HorizontalVertical"
imports_granularity = "Module"

wrap_comments = true
max_width = 80
force_multiline_blocks = true
format_strings = true
format_macro_bodies = true
format_macro_matchers = true
reorder_impl_items = true
edition = "2021"
