[package]
name = "cling"
description = "[WIP] An opinionated Rust framework for building multi-level command-line applications on top of clap.rs"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
include = ["**/*.rs", "../README.md", "../LICENSE", "../examples"]

[dependencies]
cling-derive = { path = "../cling-derive", version = "0.0.0-alpha.1", optional = true }
clap = { version = "4.3", features = ["env", "derive", "wrap_help"] }
clap-stdin = { version = "0.2.0" }
env_logger = "0.10.0"
tracing = { workspace = true }
thiserror = { workspace = true }
static_assertions = { workspace = true }
anyhow = { version = "1.0.72" }
colored = { version = "2.0.4" }
async-trait = { version = "0.1.72" }
indoc = { version = "2.0.3" }
termcolor = { version = "1.2.0" }

[dev-dependencies]
trybuild = { version = "1.0.82" }
tokio = { version = "1.29.1", features = ["full"] }

[features]
default = ["derive"]
derive = ["dep:cling-derive"]

[[example]]
name = "simple"
path = "../examples/simple.rs"

[[example]]
name = "lowlevel"
path = "../examples/lowlevel.rs"
