[package]
name = "cling"
description = "[WIP] An opinionated Rust framework for building multi-level command-line applications on top of clap.rs"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
include = ["**/*.rs", "../README.md", "../LICENSE", "../examples"]

[dependencies]
clap = { version = "4.3", features = ["env", "derive", "wrap_help"] }
clap-stdin = { version = "0.2.0" }
env_logger = "0.10.0"
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { version = "1.0.72" }
colored = { version = "2.0.4" }

[[example]]
name = "simple"
path = "../examples/simple.rs"
