[package]
name = "cling"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
include = ["**/*.rs", "../README.md", "../LICENSE", "../examples"]

[dependencies]
clap = { version = "4.3", features = ["env", "derive", "wrap_help"] }
clap-stdin = { version = "0.2.0" }
env_logger = "0.10.0"
tracing = { workspace = true }
thiserror = { workspace = true }

[[example]]
name = "simple"
path = "../examples/simple.rs"

